AWS_ACCESS_KEY_ID: "goes here"
AWS_SECRET_ACCESS_KEY: "goes here"
development:
  SENDGRID_USERNAME: "here"
  SENDGRID_PASSWORD: "here"
  AWS_BUCKET: artcaring-dev
  STRIPE_PUBLISHABLE_KEY: 
  FACEBOOK_ID: 
  FACEBOOK_SECRET:
production:
  AWS_BUCKET: artcaring-prod
  FACEBOOK_ID: 
  FACEBOOK_SECRET: