AWS_ACCESS_KEY_ID: "goes here"
AWS_SECRET_ACCESS_KEY: "goes here"
development:
  SENDGRID_USERNAME: "here"
  SENDGRID_PASSWORD: "here"
  AWS_BUCKET: artcaring-dev
production:
  AWS_BUCKET: artcaring-prod