development:
  adapter: postgresql
  encoding: unicode
  database: artcares_development
  pool: 5
  username: Scott
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: artcares_test
  pool: 5
  username: Scott
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: artcaring_production
  pool: 5
  username: Scott
  password: